version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-cloudflared-web
      APP_PORT: 3000

  web:
    image: radiokot/umbrel-cloudflared:1.0.2
    hostname: cloudflared-web
    restart: on-failure
    stop_grace_period: 1s
    depends_on:
      - connector
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      CLOUDFLARED_HOSTNAME: "cloudflared-connector"
      CLOUDFLARED_METRICS_PORT: "${APP_CLOUDFLARED_METRICS_PORT}"
      CLOUDFLARED_TOKEN_FILE: "/app/data/token"

  connector:
    image: radiokot/umbrel-cloudflared-connector:1.0.0-cf.2024.6.1
    hostname: cloudflared-connector
    restart: on-failure
    stop_grace_period: 5s
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - type: bind
        source: ${APP_DATA_DIR}/data/process.sh
        target: /process.sh
    environment:
      CLOUDFLARED_METRICS_PORT: "${APP_CLOUDFLARED_METRICS_PORT}"
      CLOUDFLARED_TOKEN_FILE: "./data/token"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${APP_DOMAIN}:host-gateway"
