version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-zlib_server_1
      APP_PORT: 7070
      PROXY_AUTH_ADD: "false"

  server:
    image: maxduke/book-searcher:latest
    restart: always