version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-zlib_server_1
      APP_PORT: 7070
      PROXY_AUTH_ADD: "false"

  server:
    image: dejavumoe/book-searcher:0.9.0
    restart: always
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/books:/books
      - ${APP_DATA_DIR}/index:/index