version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-chinesesubfinder_1
      APP_PORT: 19035

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest-lite
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
    restart: on-failure
    ports:
      - 19035:19035
      - 19037:19037 