version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-roon_server_1
      APP_PORT: 8200
      PROXY_AUTH_ADD: "false"

  server:
    image: toycon/roon:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ${APP_DATA_DIR}/data/:/var/roon
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    cap_add:
      - SYS_NICE
    ulimits:
      nofile:
        soft: 8192
        hard: 8192