version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-roon_server_1
      APP_PORT: 8099
      PROXY_AUTH_ADD: "false"

  server:
    image: suwey/streamer:latest
    command: ["1", "1", "1", "1", "8099"]
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/playlist:/playlist
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
    ports:
      - "3483:3483/tcp"
      - "3483:3483/udp"
      - "9100:9100/tcp"
      - "9003:9003/udp"
      - "9003:9003/tcp"
      - "9004:9004/tcp"
      - "9004:9004/udp"
      - "9090:9090/tcp"
      - "9000:9000/tcp"
      - "43210:43210/tcp"
      - "43210:43210/udp"
      - "8088:8088/tcp"