version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-roon_server_1
      APP_PORT: 8200
      PROXY_AUTH_ADD: "false"

  server:
    image: suwey/streamer:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/playlist:/playlist
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
    network_mode: host
    extra_hosts:
      - "bits.roonlabs.net:127.0.0.1"
      - "discovery.roonlabs.net:127.0.0.1"
      - "devicedb.roonlabs.net:127.0.0.1"
      - "updates.roonlabs.com:127.0.0.1"
      - "accounts5.roonlabs.com:127.0.0.1"
      - "metadataserver.roonlabs.net:127.0.0.1"
      - "download.roonlabs.com:127.0.0.1"
      - "prop5.roonlabs.com:127.0.0.1"
      - "push.roonlabs.com:127.0.0.1"
      - "devicedb.roonlabs.com:127.0.0.1"
      - "discover.roonlabs.net:127.0.0.1"
      - "messaging.roonlabs.net:127.0.0.1"
      - "geoip.roonlabs.net:127.0.0.1"
      - "graph.facebook.com:127.0.0.1"
