version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-roon_server_1
      APP_PORT: 8200
      PROXY_AUTH_ADD: "false"

  server:
    image: ddg5366/roonserver:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ${APP_DATA_DIR}/data/:/var/roon/RoonServer
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
    ports:
      - 55000:55000/tcp
      - 9330-9339:9330-9339/tcp
      - 30000-30009:30000-30009/tcp
      - 9003:9003/udp