version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-roon_server_1
      APP_PORT: 8200
      PROXY_AUTH_ADD: "false"

  server:
    image: ddg5366/roonserver:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/RoonServer:/var/roon/RoonServer
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
    network_mode: host