version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-alinetdisk_server_1
      APP_PORT: 5801

  server:
    image: toycon/aliyun:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - NGINX_LISTENING_PORT=5801
      - DISABLE_ALIST=true
      - ELECTRON_NO_ATTACH_CONSOLE=true
      - ELECTRON_RUN_AS_NODE=1
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
      - /var/run/dbus:/var/run/dbus
    ports:
      - 5901:5901
      - 6081:6081