version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-alinetdisk_server_1
      APP_PORT: 6080

  server:
    image: toycon/aliyun:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads