version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-alinetdisk_server_1
      APP_PORT: 5801
      PROXY_AUTH_ADD: "true"

  server:
    image: toycon/aliyunpan:latest
    restart: always
    user: "0:0"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/config/download
      - /dev/shm/xbyyunpan:/dev/shm
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket