version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-baidunetdisk_server_1
      APP_PORT: 5800
      PROXY_AUTH_ADD: "false"

  server:
    image: johngong/baidunetdisk:latest
    restart: always
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/config/baidunetdiskdownload