version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-nastools_server_1
      APP_PORT: 3000

  server:
    image: hsuyelin/nas-tools:latest
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/media
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
    restart: always