version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-clash_server_1
      APP_PORT: 9091

  server:
    image: toycon/clash:1.0.5
    restart: always
    ports:
      - 7890:7890
    volumes:
      - type: bind
        source: ${APP_DATA_DIR}/data/config/config.yaml
        target: /home/runner/.config/clash/config.yaml
        read_only: true