version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: subarashi-clash_1
      APP_PORT: 9090

  clash:
    image: navyd/clash:latest
    restart: on-failure
    # [How do I break a string in YAML over multiple lines?](https://stackoverflow.com/a/21699210/8566831)
    command: >
      -f /config.yaml
      -b clash
      -d /clash_dir
      -u nobody
      -vvv
    ports:
      - 7890:7890
      - 7891:7891
      - 7892:7892
    # 仅使用cap_add将无法代理本机docker
    # cap_add:
    # 使用clash-premium的docker镜像无法创建tun: https://github.com/Dreamacro/clash/issues/736
    #   - NET_ADMIN
    # 使用sysctl支持代理本机docker 内部流量
    privileged: true
    devices:
      - /dev/net/tun
    volumes:
      - type: bind
        source: ${APP_DATA_DIR}/data/config/config.yaml
        target: /config.yaml
        read_only: true
      - ${APP_DATA_DIR}/data/clash_dir:/clash_dir
    # 自定义dns 当clash作为本地上游dns时 clash启动时无法找到可用的dns
    dns:
      - 8.8.8.8
      - 114.114.114.114